import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

const interSans = Inter({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Monarch",
    template: "%s - Monarch",
  },
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.className} antialiased min-h-dvh flex flex-col`}
      >
        {children}
      </body>
    </html>
  );
}
